import type { Metadata } from 'next';
import { Inter, Lexend } from 'next/font/google';
import './ui/globals.css';
import SessionProvider from './ui/Providers/SessionProvider';

const inter = Inter({ subsets: ['latin'], weight: ['300', '400', '500', '700'] });
const lexend = Lexend({ subsets: ['latin'], weight: ['300', '400', '700'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='es'>
      <body className={`${lexend.className} ${inter.className}`}>
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
